image:
  repository: partofaplan/snake-game
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: snake.k3d.local
      paths:
        - path: /
          pathType: Prefix
    # Expose via sslip.io so others on LAN can resolve to 192.168.5.78
    - host: snake.192.168.5.78.sslip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # Example:
  # tls:
  #   - secretName: snake-tls
  #     hosts:
  #       - snake.example.com

resources:
  limits: { }
  requests:
    cpu: 60m
    memory: 80Mi

replicaCount: 1

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 0
  fsGroup: 0
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

podSecurityContext: {}

probes:
  liveness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 3
    periodSeconds: 5
