name: Deploy to Cloud Run (mobile)

on:
  workflow_run:
    workflows: ["Build Docker Image for Mobile (latest)"]
    types:
      - completed
  workflow_dispatch: {}

env:
  SERVICE: snake-game-mobile
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  IMAGE: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest-mobile

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'project/mobile' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE" \
            --image "$IMAGE" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --cpu 1 --memory 512Mi \
            --concurrency 500 \
            --timeout 3600 \
            --max-instances 1 \
            --min-instances 1 \
            --set-env-vars MAX_VOTES=3,DEFAULT_CREATE_MIN=5,DEFAULT_VOTING_MIN=3,DEFAULT_DISCUSS_MIN=5
